apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  namespace: comtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: schmivin/comtest-producer:0.1.0
        ports:
        - containerPort: 8080
